### ISSUE TITLE
TypeError: Cannot read property 'errorsOnly' of undefined

### ISSUE THREAD

**Issue by jamiejackson** [seancoyne/testbox-runner#13]
I haven't been able to use testbox-runner successfully yet, so I don't know if I'm doing something wrong.

I'm getting this:

```
[16:51:32] Using gulpfile /conf/gulpfile.js
[16:51:32] Starting 'watch'...
[16:51:33] Finished 'watch' after 977 ms
[16:51:33] Starting 'default'...
[16:51:33] Finished 'default' after 95 μs

// I made an edit to a CFC here

[16:51:45] Starting 'testbox'...
Running tests via URL: http://local.mysite.info/test/HTMLRunner.cfm?reporter=JSON&directory=%2Ftest%2Fmodel%2Finfo%2Fonecpd%2Fsecurity&recurse=true
/conf/node_modules/testbox-runner/lib/reporter.js:75
        if ( config.errorsOnly && ! bundle.TOTALFAIL && ! bundle.TOTALERROR ) {
                   ^
TypeError: Cannot read property 'errorsOnly' of undefined
    at outputBundle (/conf/node_modules/testbox-runner/lib/reporter.js:75:14)
    at /conf/node_modules/testbox-runner/lib/reporter.js:152:4
    at Array.forEach (native)
    at module.exports (/conf/node_modules/testbox-runner/lib/reporter.js:151:23)
    at /conf/gulpfile.js:22:5
    at Request._callback (/conf/node_modules/testbox-runner/lib/runner.js:43:4)
    at Request.self.callback (/conf/node_modules/request/request.js:373:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/conf/node_modules/request/request.js:1318:14)
```

# Configs:

## `gulpfile.js`
```js
/* jshint node: true */
(function(){

	"use strict";

	var gulp = require("gulp");

	gulp.task("testbox", function(done){
  
    // NOTE: this example assumes you have a .testbox-runnerrc file holding your config settings
  
		var rc = require("rc");
		var testboxRunner = require("testbox-runner/lib/runner.js");
		var testboxReporter = require("testbox-runner/lib/reporter.js");

		testboxRunner(rc("testbox-runner", {}), function(uri){
			console.log("Running tests via URL: " + uri);
		}, function(err, results){
			if (err) {
				console.error(err);
			} else {
				testboxReporter(results);
			}
			done();
		});

	});

	gulp.task("watch", [ ], function() {

		// cfml
		gulp.watch([ 
			// "./api/model/**/*.cfc",
			// "./api/tests/spec/**/*.cfc"
			/*
			"/var/www/vmhost/hud/hudexchange/cfml/deployment_root/test/lib/com",
			"/var/www/vmhost/hud/hudexchange/cfml/deployment_root/lib/com",
			"/var/www/vmhost/hud/hudexchange/cfml/deployment_root/test/model",
			"/var/www/vmhost/hud/hudexchange/cfml/deployment_root/model/main"
			*/
			"/code/**/*.cfc"
		], [ "testbox" ]);

	});

	gulp.task("default", [ "watch" ]);

})();
```
## `.testbox-runnerrc`

```json
{
    "runner": "http://local.hudexchange.info/test/HTMLRunner.cfm?password=opensesame",
    "directory": "/test/model/info/onecpd/security",
    "recurse": true,
    "password": "opensesame",
    "errorsOnly": false
}
```

**Comment by jinglesthula** [comment]
I'm getting the same.  Likely this is due to this project having worked at one time with an older version of TestBox, but not being maintained and tested against newer versions.  It hasn't seen commits in over 2 years.  Since I'm going to need it, I may fork it and see if I can fix it.

_edit_: I'm seeing that the `outputBundle` function in `reporter.js` is looking for all-caps keys in `bundle`, where TestBox is providing them in camelCase.
