### ISSUE TITLE
Cannot read 'bundleStats' of undefined

### ISSUE THREAD

**Issue by sosensible** [seancoyne/testbox-runner#14]
Here is a output sample. Just NPM installed today, so running current version.

```
PS C:\dev\branch\pfm_api> testbox-runner --config textbox.json
Running tests via URL: http://jfarrar.pfm.local.dev:81/testbox/system/runners/HTMLRunner.cfm?reporter=JSON&directory=%2Ftests&recurse=true

C:\Program Files\nodejs\node_modules\testbox-runner\lib\reporter.js:146
                if (!results.bundleStats || !results.bundleStats.length) {
                            ^

TypeError: Cannot read property 'bundleStats' of undefined
    at module.exports (C:\Program Files\nodejs\node_modules\testbox-runner\lib\reporter.js:146:15)
    at C:\Program Files\nodejs\node_modules\testbox-runner\index.js:59:3
    at Request._callback (C:\Program Files\nodejs\node_modules\testbox-runner\lib\runner.js:43:4)
    at Request.self.callback (C:\Program Files\nodejs\node_modules\testbox-runner\node_modules\request\request.js:373:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Program Files\nodejs\node_modules\testbox-runner\node_modules\request\request.js:1318:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\testbox-runner\node_modules\request\request.js:1266:12)
```

**Comment by phoenixfangor** [comment]
I'm getting a related error with testbox version 2.5.x
![bundlesuitefailuretestbox-runner](https://user-images.githubusercontent.com/1885171/45848106-dd8e5400-bcf2-11e8-8599-fc7ee5d85f8d.png)
AND, if I try to run without bundles, I get zero results.
